#!/usr/bin/env python3
"""Generate the Gradient dither threshold tables (ADR 0028) for BOTH the engine and the shell.

Emits, byte-identically from one run:
  crates/engine/src/tool/dither_tables.g.rs      (the engine dithers with these)
  app/lib/editor/patterns/dither_tables.g.dart   (the shell previews with the same numbers)

Tables:
  BLUE_NOISE  64x64 void-and-cluster (Ulichney 1993) threshold matrix, a permutation of 0..4095,
              from a fixed seed so a rerun reproduces the committed bytes.
  HALFTONE4/8 clustered-dot ("halftone") matrices: cells ranked by distance from the tile center,
              ties broken by angle (clockwise from the upper-left), so the dot grows round from the
              middle and the last cells are the four corners, where neighboring tiles' corners meet
              as a shrinking hole. The 4x4 is the textbook clustered-dot matrix.

Run:  python tools/dither/gen_tables.py      (needs numpy; deterministic, safe to rerun)
"""
import math
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RS = os.path.join(ROOT, "crates", "engine", "src", "tool", "dither_tables.g.rs")
DART = os.path.join(ROOT, "app", "lib", "editor", "patterns", "dither_tables.g.dart")

N = 64          # blue-noise side
SIGMA = 1.9     # Ulichney's Gaussian energy filter width
SEED = 20260906


def kernel():
    k = np.zeros((N, N))
    for dy in range(N):
        for dx in range(N):
            wy = min(dy, N - dy)
            wx = min(dx, N - dx)
            k[dy, dx] = math.exp(-(wx * wx + wy * wy) / (2 * SIGMA * SIGMA))
    return k


def blue_noise():
    K = kernel()
    rng = np.random.default_rng(SEED)

    def energy_of(pat):
        e = np.zeros((N, N))
        for (y, x) in zip(*np.nonzero(pat)):
            e += np.roll(K, (y, x), axis=(0, 1))
        return e

    # A random ~10 % initial pattern, relaxed until the tightest cluster is the largest void.
    pat = np.zeros((N, N), dtype=np.int8)
    ones = N * N // 10
    idx = rng.choice(N * N, ones, replace=False)
    pat.flat[idx] = 1
    E = energy_of(pat)
    while True:
        tc = np.unravel_index(np.argmax(np.where(pat == 1, E, -np.inf)), (N, N))
        pat[tc] = 0
        E -= np.roll(K, tc, axis=(0, 1))
        lv = np.unravel_index(np.argmin(np.where(pat == 0, E, np.inf)), (N, N))
        pat[lv] = 1
        E += np.roll(K, lv, axis=(0, 1))
        if lv == tc:
            break

    rank = np.full((N, N), -1, dtype=np.int32)
    initial = pat.copy()
    E0 = E.copy()

    # Phase 1: remove tightest clusters, ranks ones-1 .. 0.
    p = initial.copy()
    E = E0.copy()
    r = int(p.sum()) - 1
    while r >= 0:
        tc = np.unravel_index(np.argmax(np.where(p == 1, E, -np.inf)), (N, N))
        p[tc] = 0
        E -= np.roll(K, tc, axis=(0, 1))
        rank[tc] = r
        r -= 1

    # Phase 2: fill largest voids, ranks ones .. N²/2 - 1.
    p = initial.copy()
    E = E0.copy()
    r = int(p.sum())
    while r < N * N // 2:
        lv = np.unravel_index(np.argmin(np.where(p == 0, E, np.inf)), (N, N))
        p[lv] = 1
        E += np.roll(K, lv, axis=(0, 1))
        rank[lv] = r
        r += 1

    # Phase 3: the zeros are now the minority; keep filling where the zeros cluster tightest.
    q = 1 - p
    E = energy_of(q)
    while r < N * N:
        tc = np.unravel_index(np.argmax(np.where(q == 1, E, -np.inf)), (N, N))
        q[tc] = 0
        E -= np.roll(K, tc, axis=(0, 1))
        rank[tc] = r
        r += 1

    assert sorted(rank.flatten().tolist()) == list(range(N * N))
    return rank


def halftone(n):
    c = (n - 1) / 2.0
    cells = []
    for y in range(n):
        for x in range(n):
            dx, dy = x - c, y - c
            d2 = round((dx * dx + dy * dy) * 4)  # integer: avoids float-tie noise
            cells.append((d2, math.atan2(dy, dx), y, x))
    cells.sort()
    m = [[0] * n for _ in range(n)]
    for rank, (_, _, y, x) in enumerate(cells):
        m[y][x] = rank
    return m


def checksum(values):
    # FNV-1a 32 over the little-endian u16 stream: pinned by the Rust and Dart tests.
    h = 0x811C9DC5
    for v in values:
        for b in (v & 0xFF, v >> 8):
            h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


def main():
    bn = blue_noise()
    h4, h8 = halftone(4), halftone(8)
    flat = bn.flatten().tolist()
    cs = checksum(flat)
    print(f"blue-noise checksum 0x{cs:08X}")
    assert h4 == [[12, 5, 6, 13], [4, 0, 1, 7], [11, 3, 2, 8], [15, 10, 9, 14]], h4

    head = "GENERATED by tools/dither/gen_tables.py (ADR 0028) -- do not edit; rerun the script."
    rows = lambda m, ind: ",\n".join(ind + "[" + ", ".join(str(v) for v in row) + "]" for row in m)
    bn_rows = ",\n".join("    " + ", ".join(str(v) for v in flat[i:i + 16]) for i in range(0, len(flat), 16))

    with open(RS, "w", newline="\n", encoding="utf-8") as f:
        f.write(f"//! {head}\n//!\n")
        f.write("//! `BLUE_NOISE` is a 64×64 void-and-cluster threshold matrix (a permutation of 0..4096, row-major);\n")
        f.write("//! `HALFTONE4`/`HALFTONE8` are clustered-dot matrices ranked by distance from the tile center.\n\n")
        f.write("pub const BLUE_NOISE_SIDE: usize = 64;\n")
        f.write(f"/// FNV-1a 32 over the little-endian u16 stream: `0x{cs:08X}` (pinned by a test).\n")
        f.write(f"pub const BLUE_NOISE_CHECKSUM: u32 = 0x{cs:08X};\n")
        f.write("#[rustfmt::skip]\npub const BLUE_NOISE: [u16; 4096] = [\n" + bn_rows + ",\n];\n\n")
        f.write("#[rustfmt::skip]\npub const HALFTONE4: [[u8; 4]; 4] = [\n" + rows(h4, "    ") + ",\n];\n\n")
        f.write("#[rustfmt::skip]\npub const HALFTONE8: [[u8; 8]; 8] = [\n" + rows(h8, "    ") + ",\n];\n")

    with open(DART, "w", newline="\n", encoding="utf-8") as f:
        f.write(f"// {head}\n//\n")
        f.write("// The same threshold tables the engine dithers gradients with, for the shell's previews:\n")
        f.write("// a 64×64 void-and-cluster blue-noise matrix (row-major permutation of 0..4096) and the two\n")
        f.write("// clustered-dot halftone matrices.\n\n")
        f.write("const int kBlueNoiseSide = 64;\n")
        f.write(f"const int kBlueNoiseChecksum = 0x{cs:08X};\n")
        f.write("const List<int> kBlueNoise = [\n" + bn_rows + ",\n];\n\n")
        f.write("const List<List<int>> kHalftone4 = [\n" + rows(h4, "  ") + ",\n];\n\n")
        f.write("const List<List<int>> kHalftone8 = [\n" + rows(h8, "  ") + ",\n];\n")
    print("wrote", RS, "and", DART)


if __name__ == "__main__":
    sys.exit(main())
