# Build the FINAL approved icon set: the SVG design record (svg/), a roundtrip
# verification page (roundtrip.html), and the generated Dart vector data
# (app/lib/editor/makapix_icons.g.dart). Run from anywhere:
#   python tools/icons/build_final.py
import os

import gen_icons as g
import svg2dart as cv

HERE = os.path.dirname(os.path.abspath(__file__))
DART_OUT = os.path.normpath(os.path.join(
    HERE, "..", "..", "app", "lib", "editor", "makapix_icons.g.dart"))

# User-approved picks (2026-07-16): round-1 designs (B1) for 9 tools,
# Select B2, Lasso B2, Onion B1.
FINAL = [
    ("pencil", "Pencil", g.S["pencil"]),
    ("airbrush", "Airbrush", g.S["airbrush"]),
    ("eraser", "Eraser", g.S["eraser"]),
    ("fill", "Bucket", g.S["fill"]),
    ("line", "Line", g.S["line"]),
    ("pick", "Eyedropper", g.S["pick"]),
    ("selColor", "SelectByColor", g.S["selcolor"]),
    ("selLyr", "SelectLayer", g.S["sellyr"]),
    ("flip", "Flip", g.S["flip"]),
    ("select", "SelectShape", g.V["select"][0]),
    ("lasso", "SelectFree", g.V["lasso"][0]),
    ("onion", "Onion", g.S["onion"]),
]


def build():
    rows, dart = [], []
    all_names = []
    os.makedirs(os.path.join(HERE, "svg"), exist_ok=True)
    for name, dsl, body in FINAL:
        segs = cv.svg_to_segs(body)
        orig = g.smooth_svg(body)
        conv = cv.segs_to_svg(segs)
        dart.append(cv.segs_to_dart(name, segs))
        all_names.append(name)
        with open(os.path.join(HERE, "svg", name + ".svg"), "w", encoding="utf-8") as f:
            f.write(orig)
        cells = ""
        for svg in (orig, conv):
            cells += (f'<td><div class="chip light">{g.sz(svg, 18)}{g.sz(svg, 48)}</div>'
                      f'<div class="chip dark">{g.sz(svg, 18)}{g.sz(svg, 48)}</div></td>')
        rows.append(f"<tr><th><b>{name}</b><small>{dsl}</small></th>{cells}</tr>")

    html = f'''<meta charset="utf-8"><title>Roundtrip check — original vs converted</title>
<style>
 body {{ font: 15px/1.5 system-ui, sans-serif; margin: 24px auto; max-width: 900px; }}
 .ic {{ display:inline-flex }} .ic svg {{ width:100%; height:100% }}
 .chip {{ display:inline-flex; gap:10px; padding:6px 10px; border-radius:9px; margin:2px }}
 .light {{ background:#f2f2f5; color:#2a2a33 }} .dark {{ background:#1d1d24; color:#d9d9e3 }}
 th, td {{ padding: 6px 10px; text-align:left; border-top:1px solid #eee }}
 th small {{ display:block; font-weight:normal; color:#888 }}
</style>
<h1>Roundtrip: original (left) vs converted cubics+flattened dashes (right)</h1>
<table><thead><tr><th>Icon</th><th>Original SVG</th><th>Converted</th></tr></thead>
{"".join(rows)}</table>'''
    with open(os.path.join(HERE, "roundtrip.html"), "w", encoding="utf-8") as f:
        f.write(html)

    names_list = ", ".join(all_names)
    dart_src = f'''// GENERATED by tools/icons/build_final.py — DO NOT EDIT BY HAND.
// Source designs: tools/icons/gen_icons.py (+ user approval 2026-07-16).
// Regenerate: python tools/icons/build_final.py
part of 'makapix_icon.dart';

/// The approved custom tool icons (24x24 design grid).
class MpxIcons {{
  MpxIcons._();

{chr(10).join(dart)}

  /// Every generated icon, for tests and previews.
  static const all = <MpxIcon>[{names_list}];
}}
'''
    with open(DART_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(dart_src)
    print(f"OK: svg/ + roundtrip.html + {DART_OUT} ({len(FINAL)} icons)")


if __name__ == "__main__":
    build()
