//! Pins the `.mkps` v1 format bytes forever: the committed fixture (generated by the CLI from
//! examples/scene/bounce.txt) must load, re-save byte-identically, and composite to the pinned
//! hash. If `fixture_bytes_are_stable` fails, the format changed — a versioning event, never a
//! refactor detail (the `.mkpx` container_fixture.rs discipline).

use makapix_scene::SceneSession;

const FIXTURE: &[u8] = include_bytes!("fixtures/bounce_v1.mkps");

#[test]
fn fixture_bytes_are_stable() {
    let mut s = SceneSession::empty();
    s.load_bytes(FIXTURE).expect("fixture loads");
    assert_eq!(s.size(), (64, 64));
    assert_eq!(s.frame_count(), 25);
    assert_eq!(s.scene.cast.len(), 1);
    assert_eq!(s.scene.actors.len(), 1);
    assert_eq!(s.save_bytes(), FIXTURE, "save(load(fixture)) must be byte-identical");
}

#[test]
fn fixture_composites_to_pinned_hash() {
    let mut s = SceneSession::empty();
    s.load_bytes(FIXTURE).expect("fixture loads");
    // The bounce example's mid-drop frame — pinned across platforms and refactors.
    assert_eq!(format!("{:016x}", s.frame_hash(12)), "f5fe324aefc6d6ac");
}
